site_name: IAW Daniel Magaña

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Primer Trimestre:
      - Práctica 6: 6-prestasho-ansible.md
      - Práctica 9: 9-practica.md
    - Segundo Trimestre:
      - Práctica 13_4: practica13_4.md
      - Práctica 14_1: 14_1-wordpress-docker-compose.md


theme:
  name: material

  palette:
    primary: green
