site_name: IAW Daniel Magaña

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Primer Trimestre:
      - Práctica 1: 6-prestasho-ansible.md
      - Práctica 2: practica2.md
    - Segundo Trimestre:
      - Práctica 14_1: 14.1-wordpress-docker-compose.md
      - Práctica 13_2: practica13_.md

theme:
  name: material

  palette:
    primary: green
